import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import StoreProvider from "~/app/StoreProvider";

export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{ children: React.ReactNode; modal: React.ReactNode }>) {
  return (
    <StoreProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body>
          <div>{children}</div>
          <div>{modal}</div>
        </body>
      </html>
    </StoreProvider>
  );
}
